float rand( vec2 pos ) {
    return fract(sin(dot(pos.xy ,vec2(12.9898,78.233))) * 43758.5453);
}

uint rand ( uint x ) {
    x ^= x >> 16;
    x *= 0x7feb352dU;
    x ^= x >> 15;
    x *= 0x846ca68bU;
    x ^= x >> 16;
    return x;
}


float rand ( vec3 pos ) {
    return rand( vec2( rand( pos.xy ), pos.z ) );
}

float rand ( vec4 pos ) {
    return rand( vec2( rand( pos.xy ), rand( pos.zw ) ) );
}